bad_folder: '../dataset/dataset-cifar10-badnet-trigger_image_grid'
good_folder: '../dataset/dataset-cifar10-good'
train_batch_size: 128
train_lr: 8e-5
train_num_steps: 100000
gradient_accumulate_every: 2
ema_decay: 0.995
amp: True
calculate_fid: True
ratio: 0.1
results_folder: "results_test"
server: 'pc'
save_and_sample_every: 0 # if 0, means not save before whole train end