dataset_name: celeba
attack: blended
trigger_name: hello_kitty.jpeg
device: cuda:0
server: pc
batch: 1024
epoch: 2000000
save_epoch: 400000
defaults:
  - noise_predictor: default
  - trainer: default
  - diffusion: scale_64
  - dataset: default
