dataset_name: celeba
attack: blended
trigger_name: hello_kitty.jpeg
device: cuda:0
server: pc
batch: 16
epoch: 500000
save_epoch: 0
defaults:
  - noise_predictor: celeba
  - trainer: default
  - diffusion: scale_64
  - dataset: default
