dataset_name: celeba
attack: blended
trigger_name: hello_kitty.jpeg
device: cuda:0
batch: 32
epoch: 500000
save_epoch: 0
ratio: 0.1
defaults:
  - noise_predictor: celeba
  - trainer: default
  - diffusion: scale_64
