dataset_name: celeba
attack: badnet
trigger_name: trigger_64_6.png
device: cuda:0
server: pc
batch: 32
epoch: 500000
save_epoch: 0
defaults:
  - noise_predictor: dim_128
  - trainer: default
  - diffusion: scale_64
  - dataset: default
