dataset_name: cifar10
attack: blended
trigger_name: hello_kitty.jpeg
device: cuda:0
batch: 16
epoch: 500000
save_epoch: 0
defaults:
  - noise_predictor: default
  - trainer: default
  - diffusion: scale_32
  - dataset: default
