dataset_name: cifar10
attack: benign
device: cuda:0
batch: 128
epoch: 700000
save_epoch: 100000
lr: 2e-4
loss_type: l2
sample_type: ddim
image_size: 32
server: pc
grad_acc: 1
parallel: 0

unet:
  dim: 128
  dim_mults: (1, 2, 2, 2)
  dropout: 0.1

diffusion:
  timesteps: 1000
  sampling_timesteps: 250
  beta_schedule: sigmoid

# only backdoor diffusion will use this
ratio: 0.1
gamma: 1e-3
p_start: 200
p_end: 400
