dataset_name: imagenette
device: cuda:0
batch: 4
epoch: 1e8
save_epoch: 10000
sample_epoch: 10000
lr: 8e-5

loss_type: l2
image_size: 128
grad_acc: 1
parallel: 0
path: None
mode: train

unet:
  dim: 128
  out_dim: 2
  dim_mults: (1, 2, 3, 3)
  dropout: 0.1

encoder:
  channels: 1
  dropout: 0.1
  self_condition: false
  dim: 128
  dim_mults: (1, 2, 3, 3)

diffusion:
  train:
    timesteps: 350
    beta_schedule: linear
    beta_start: 1e-4
    beta_end: 2e-2
  test:
    timesteps: 350
    beta_schedule: linear
    beta_start: 1e-4
    beta_end: 2e-2

# only backdoor diffusion will use this
ratio: 0.1
gamma: 1e-3
p_start: 100
p_end: 200


defaults:
  - attack: benign