dataset_name: cifar10
attack: badnet
trigger_name: trigger_32_3.png
device: 'cuda:0'
server: pc
defaults:
  - noise_predictor: default
  - trainer: default
  - diffusion: default
  - dataset: default
