task_name: default
dataset_name: celebahq
device: cuda:0
batch: 2
epoch: 1e8
save_epoch: 10000
sample_epoch: 50000
sample_num: 4
lr: 8e-5
loss_type: l2
sample_type: ddim
image_size: 256
grad_acc: 1
parallel: 0
path: None
mode: train

unet:
  dim: 128
  # dim_mults: (1, 2, 4, 4, 8)
  dim_mults: (1, 1, 2, 2, 4)
  dropout: 0

diffusion:
  sampling_timesteps: 250
  timesteps: 1000
  beta_schedule: linear
  beta_start: 1e-4
  beta_end: 2e-2

# only backdoor diffusion will use this
ratio: 0.1
gamma: 1e-3
p_start: 100
p_end: 200


defaults:
  - attack: benign
  - artifact: benign