dataset_name: gtsrb
attack: blended
trigger_name: hello_kitty.jpeg
device: cuda:0
batch: 128
epoch: 600000
save_epoch: 0
ratio: 0.1
defaults:
  - noise_predictor: gtsrb
  - trainer: default
  - diffusion: scale_32
