dataset_name: gtsrb
attack: badnet
trigger_name: trigger_32_3.png
device: cuda:0
batch: 64
epoch: 500000
save_epoch: 0
ratio: 0.1
defaults:
  - noise_predictor: dim_128
  - trainer: default
  - diffusion: scale_32
  - dataset: default