dataset_name: gtsrb
attack: benign
device: cuda:0
batch: 128
epoch: 700000
save_epoch: 5000
lr: 8e-5
loss_type: l2
sample_type: ddim
image_size: 32
server: pc
grad_acc: 2


unet:
  dim: 64
  dim_mults: (1, 2, 2, 2)
  dropout: 0

diffusion:
  timesteps: 1000
  sampling_timesteps: 250
  beta_schedule: linear

# only backdoor diffusion will use this
ratio: 0.1
gamma: 1e-3
p_start: 100
p_end: 200

