attack: badnet
trigger_name: trigger_image_grid.png
trigger_path: ../resource/${attack}/${trigger_name}
dataset: cifar10
generate_path: ./dataset-${dataset}-bad
good_generate_path: ./dataset-${dataset}-good
all_generate_path: ./dataset-${dataset}-all
batch: 64
num_workers: 4
part: 0.8
mix_factor: 0.5
device: cuda:0

