attack: ${attack}
trigger_path: ../resource/${attack}/${trigger_name}
generate_path: ../dataset/dataset-${dataset_name}-bad
good_generate_path: ../dataset/dataset-${dataset_name}-good
all_generate_path: ../dataset/dataset-${dataset_name}-all
batch: 64
num_workers: 4
part: 0.8
mix_factor: 0.5
device: cuda:0

