image_size: 32
timesteps: 1000
sampling_timesteps: 250
objective: pred_noise
attack: blended
trigger: ../resource/${attack}/${trigger_name}
factor_list: [1, 1]
device: cuda:0
reverse_step: 6 # max 6, if 7, the memory is not enough