image_size: 64
timesteps: 1000
sampling_timesteps: 250
objective: pred_noise
attack: ${attack}
trigger: ../resource/${attack}/${trigger_name}
factor_list: [1, 1]
device: ${device}
reverse_step: 3 # max 6, if 7, the memory is not enough
gamma: 1e-3