attack: badnet
triger_name: trigger_image_grid
triger_path: ../resource/${attack}/${triger_name}.png
dataset: cifar10
generate_path: ./dataset-${dataset}-${attack}-${triger_name}
good_generate_path: ./dataset-${dataset}-good
all_generate_path: ./dataset-${dataset}-all
batch: 64
num_workers: 4
part: 0.8
device:
  list: [0, 1]
  id: 0
  cuda: cuda:${device.id}

